# =============================================================================
# 경로 계획 파라미터 설정
# DWA 알고리즘의 경로 평가 및 궤적 생성 관련 설정
# =============================================================================

DWAPlannerROS:
  # 경로 평가 가중치 설정
  path_distance_bias: 80.0      # 글로벌 경로 따르기 가중치
  goal_distance_bias: 15.0      # 목표점 도달 가중치
  occdist_scale: 0.08           # 장애물 회피 가중치
  forward_point_distance: 0.325 # 로봇 앞쪽 참조점 거리 (m)
  
  # 궤적 시뮬레이션 설정
  sim_time: 2.5           # 경로 시뮬레이션 시간 (s)
  sim_granularity: 0.02   # 시뮬레이션 단계 크기 (m)
  vx_samples: 15          # x 속도 샘플 수
  vy_samples: 0           # y 속도 샘플 수 (비홀로노믹 로봇이므로 0)
  vth_samples: 80         # 회전 속도 샘플 수
  
  # 제어 주기 설정
  controller_frequency: 10.0  # 컨트롤러 주기 (Hz)
  
  # 시각화 설정
  publish_traj_pc: true        # 궤적 포인트 클라우드 발행
  publish_cost_grid_pc: true   # 비용 그리드 발행
  global_frame_id: utm_local   # 전역 프레임 ID

# =============================================================================
# Move Base 일반 설정
# =============================================================================

# 제어 주기 설정
controller_frequency: 10.0
planner_frequency: 5.0
controller_patience: 15.0
planner_patience: 5.0

# 진동 감지 및 복구 설정
oscillation_timeout: 10.0     # 진동 감지 시간 (초)
oscillation_distance: 0.5     # 진동 감지 거리 (m)
recovery_behavior_enabled: true
clearing_rotation_allowed: true
conservative_clear_costmap: true

# 플래너 설정
base_local_planner: dwa_local_planner/DWAPlannerROS
base_global_planner: global_planner/GlobalPlanner

# =============================================================================
# Global Planner 설정
# =============================================================================

GlobalPlanner/allow_unknown: true
GlobalPlanner/use_dijkstra: true
GlobalPlanner/use_quadratic: true
GlobalPlanner/use_grid_path: false
GlobalPlanner/old_navfn_behavior: false