# =============================================================================
# 경로 계획 파라미터 설정
# DWA 알고리즘의 경로 평가 및 궤적 생성 관련 설정
# =============================================================================

DWAPlannerROS:
  # ==========================================================================
  # 경로 평가 가중치 설정 (궤적 선택 시 각 요소의 중요도)
  # ==========================================================================
  path_distance_bias: 80.0      # 글로벌 경로 따르기 가중치 (높을수록 계획된 경로를 잘 따름)
  goal_distance_bias: 15.0      # 목표점 도달 가중치 (높을수록 목표점으로 직진하려 함)
  occdist_scale: 0.08           # 장애물 회피 가중치 (높을수록 장애물을 더 멀리 피함)
  forward_point_distance: 0.325 # 로봇 앞쪽 참조점 거리 (m) - 로봇이 얼마나 앞을 내다보는지
  
  # ==========================================================================
  # 궤적 시뮬레이션 설정 (DWA 알고리즘의 핵심 파라미터)
  # ==========================================================================
  sim_time: 2.5           # 경로 시뮬레이션 시간 (s) - 얼마나 미래를 예측할지
  sim_granularity: 0.02   # 시뮬레이션 단계 크기 (m) - 궤적 정밀도 (작을수록 정확하지만 계산량 증가)
  vx_samples: 15          # x 속도 샘플 수 - 전진/후진 속도 조합 개수
  vy_samples: 0           # y 속도 샘플 수 (비홀로노믹 로봇이므로 0) - 옆으로 이동 불가
  vth_samples: 80         # 회전 속도 샘플 수 - 회전 속도 조합 개수 (많을수록 부드러운 회전)
  
  # ==========================================================================
  # 제어 주기 설정
  # ==========================================================================
  controller_frequency: 10.0  # 컨트롤러 주기 (Hz) - 1초에 몇 번 궤적을 계산할지
  
  # ==========================================================================
  # 시각화 설정 (디버깅 및 모니터링용)
  # ==========================================================================
  publish_traj_pc: true        # 궤적 포인트 클라우드 발행 - RViz에서 후보 궤적들 확인 가능
  publish_cost_grid_pc: true   # 비용 그리드 발행 - 각 궤적의 비용 시각화
  global_frame_id: utm_local   # 전역 프레임 ID - 좌표계 설정

# =============================================================================
# Move Base 일반 설정 (네비게이션 시스템 전반적인 동작 제어)
# =============================================================================

# ==========================================================================
# 제어 주기 설정 (시스템 반응 속도)
# ==========================================================================
controller_frequency: 10.0  # 로컬 플래너 실행 주기 (Hz) - 장애물 회피 반응 속도
planner_frequency: 5.0       # 글로벌 플래너 실행 주기 (Hz) - 전체 경로 재계산 빈도
controller_patience: 15.0    # 로컬 플래너 대기 시간 (s) - 이 시간 내에 유효한 명령이 없으면 복구 시작
planner_patience: 5.0        # 글로벌 플래너 대기 시간 (s) - 경로 계획 실패 시 복구까지 대기 시간

# ==========================================================================
# 진동 감지 및 복구 설정 (로봇이 같은 곳을 맴돌 때 감지)
# ==========================================================================
oscillation_timeout: 10.0     # 진동 감지 시간 (초) - 이 시간 동안 진동하면 복구 동작 시작
oscillation_distance: 0.5     # 진동 감지 거리 (m) - 이 거리 내에서 왔다갔다 하면 진동으로 판단
recovery_behavior_enabled: true    # 복구 동작 활성화 - 막혔을 때 자동으로 복구 시도
clearing_rotation_allowed: true    # 코스트맵 클리어링 시 회전 허용 - 장애물 정보 갱신을 위한 회전
conservative_clear_costmap: true   # 보수적 코스트맵 클리어링 - 안전하게 장애물 정보 갱신

# ==========================================================================
# 플래너 설정 (사용할 알고리즘 지정)
# ==========================================================================
base_local_planner: dwa_local_planner/DWAPlannerROS  # 로컬 플래너 - 장애물 회피 및 즉각적인 경로 수정
base_global_planner: global_planner/GlobalPlanner   # 글로벌 플래너 - 전체 경로 계획

# =============================================================================
# Global Planner 설정 (전체 경로 계획 알고리즘 세부 설정)
# =============================================================================

GlobalPlanner/allow_unknown: true      # 미지의 영역 통과 허용 - 맵에 없는 구역도 지나갈 수 있음
GlobalPlanner/use_dijkstra: true       # 다익스트라 알고리즘 사용 - 최단 경로 보장
GlobalPlanner/use_quadratic: true      # 2차 근사 사용 - 더 부드러운 경로 생성
GlobalPlanner/use_grid_path: false     # 그리드 경로 사용 안함 - 대각선 이동 허용
GlobalPlanner/old_navfn_behavior: false # 구형 navfn 동작 사용 안함 - 개선된 알고리즘 사용