# =============================================================================
# 로봇 동역학 파라미터 설정
# Husky A200 사양에 맞는 속도 및 가속도 제한 설정
# =============================================================================

DWAPlannerROS:
  # ==========================================================================
  # 속도 제한 설정 (로봇의 물리적 한계 정의)
  # ==========================================================================
  max_vel_x: 1.0      # 최대 전진 속도 (m/s) - 로봇이 낼 수 있는 최고 속도
  min_vel_x: -1.0     # 최소 전진 속도 (m/s) - 후진 시 최대 속도 (음수)
  max_vel_y: 0.0      # 최대 Y축 속도 (비홀로노믹 로봇이므로 0) - 옆으로 이동 불가
  min_vel_y: 0.0      # 최소 Y축 속도 (비홀로노믹 로봇이므로 0) - 옆으로 이동 불가
  max_vel_trans: 1.0  # 최대 이동 속도 (m/s) - 실제 사용할 최대 속도 제한
  min_vel_trans: 0.1  # 최소 이동 속도 (m/s) - 너무 느린 움직임 방지
  max_vel_theta: 0.8  # 최대 회전 속도 (rad/s) - 제자리 회전 시 최대 각속도
  min_vel_theta: 0.08 # 최소 회전 속도 (rad/s) - 너무 느린 회전 방지
  
  # ==========================================================================
  # 가속도 제한 설정 (급격한 속도 변화 방지)
  # ==========================================================================
  acc_lim_x: 3.0      # X축 가속도 제한 (m/s^2) - 전진/후진 가속도 한계
  acc_lim_y: 0.0      # Y축 가속도 제한 (m/s^2) - 비홀로노믹 로봇이므로 0
  acc_lim_theta: 1.0  # 회전 가속도 제한 (rad/s^2) - 급격한 방향 전환 방지
  
  # ==========================================================================
  # 목표 도달 허용치 (언제 목표에 도달했다고 판단할지)
  # ==========================================================================
  xy_goal_tolerance: 3        # 위치 허용 오차 (m) - 목표점으로부터 이 거리 내에 있으면 도달로 판단
  yaw_goal_tolerance: 3.14    # 방향 허용 오차 (rad) - 목표 방향과 이 각도 차이 내에 있으면 도달로 판단
  latch_xy_goal_tolerance: true  # 위치 도달 후 회전만 허용 - 위치 도달 후 제자리에서 방향만 조정
  
  # ==========================================================================
  # 로봇 행동 설정 (움직임 특성 조정)
  # ==========================================================================
  penalize_negative_x: false  # 후진 패널티 설정 - false면 후진도 허용, true면 후진보다 회전 선호
  
  # ==========================================================================
  # 안전 설정 (충돌 방지 및 안전한 정지)
  # ==========================================================================
  stop_time_buffer: 0.2       # 정지 시간 버퍼 (s) - 장애물 감지 시 안전하게 정지하기 위한 여유 시간
  scaling_speed: 0.25         # 속도 스케일링 임계값 (m/s) - 이 속도 이하에서는 회전 반경 축소
  max_scaling_factor: 0.2     # 최대 스케일링 팩터 - 속도 스케일링 시 최대 축소 비율
  
  # ==========================================================================
  # 진동 방지 (같은 지점에서 계속 맴도는 현상 방지)
  # ==========================================================================
  oscillation_reset_dist: 0.1 # 진동 감지 거리 (m) - 이 거리 내에서 왔다갔다 하면 진동으로 판단하여 리셋